#!/usr/bin/env Rscript

suppressPackageStartupMessages({library(Seurat);library(SeuratObject);library(data.table);library(ggplot2);library(scattermore);library(patchwork)})
parse_args<-function(x){o<-list();i<-1L;while(i<=length(x)){k<-sub("^--","",x[i]);if(i==length(x)||startsWith(x[i+1],"--")){o[[k]]<-TRUE;i<-i+1L}else{o[[k]]<-x[i+1];i<-i+2L}};o};a<-parse_args(commandArgs(trailingOnly=TRUE))
need<-c("rds","metadata","out","cell-id-col","broad-col","subtype-col");m<-need[!need%in%names(a)];if(length(m))stop("Missing: ",paste(m,collapse=", "))
dir.create(a$out,recursive=TRUE,showWarnings=FALSE);node_dir<-file.path(a$out,"spatial_nodes");dir.create(node_dir,showWarnings=FALSE);fig<-file.path(a$out,"figures");dir.create(fig,showWarnings=FALSE)
read_any<-function(p)if(grepl("\\.gz$",p))fread(cmd=paste("gzip -dc",shQuote(p)))else fread(p)
save_both<-function(p,stem,w=9,h=7){ggsave(paste0(stem,".png"),p,width=w,height=h,dpi=400,bg="white",limitsize=FALSE);ggsave(paste0(stem,".pdf"),p,width=w,height=h,device=cairo_pdf,bg="white",limitsize=FALSE)}
safe<-function(x)substr(gsub("_+","_",gsub("[^A-Za-z0-9_.-]+","_",x)),1,150)
obj<-readRDS(a$rds);meta<-read_any(a$metadata);cc<-a$`cell-id-col`;meta[[cc]]<-as.character(meta[[cc]]);stopifnot(uniqueN(meta[[cc]])==nrow(meta));cells<-intersect(colnames(obj),meta[[cc]]);if(!length(cells))stop("No matching IDs");meta<-meta[match(cells,get(cc))]
plot_map<-function(d,group,title,stem,spatial=FALSE){d[,label:=as.character(get(group))];d<-d[!is.na(label)&nzchar(label)];lev<-sort(unique(d$label));pal<-setNames(hcl.colors(length(lev),"Dynamic"),lev);p<-ggplot(d,aes(x,y,colour=label))+scattermore::geom_scattermore(pointsize=ifelse(spatial,.5,.65),pixels=c(2200,2200))+scale_colour_manual(values=pal)+theme_classic(base_size=8)+labs(title=title,colour=NULL);if(spatial)p<-p+scale_y_reverse()+coord_equal()+theme_void()+labs(title=title);save_both(p,stem)}
if(!is.null(a$umap)){um<-read_any(a$umap);um[[cc]]<-as.character(um[[cc]]);um<-um[match(cells,get(cc))];ux<-intersect(c("UMAP_1","umap_1","UMAP1"),names(um))[1];uy<-intersect(c("UMAP_2","umap_2","UMAP2"),names(um))[1];ud<-data.table(cell_id=cells,x=um[[ux]],y=um[[uy]])}else if(inherits(obj,"Seurat")){red<-ifelse(is.null(a$reduction),"umap",a$reduction);em<-Embeddings(obj,red)[cells,1:2,drop=FALSE];ud<-data.table(cell_id=cells,x=em[,1],y=em[,2])}else if(inherits(obj,"SingleCellExperiment")){if(!requireNamespace("SingleCellExperiment",quietly=TRUE))stop("SingleCellExperiment package required");red<-ifelse(is.null(a$reduction),"UMAP",a$reduction);em<-SingleCellExperiment::reducedDim(obj,red)[cells,1:2,drop=FALSE];ud<-data.table(cell_id=cells,x=em[,1],y=em[,2])}else stop("Supply --umap for this object class")
ud<-cbind(ud,meta[,.(broad=get(a$`broad-col`),subtype=get(a$`subtype-col`))]);has_subtype<-any(!is.na(ud$subtype)&nzchar(as.character(ud$subtype)));plot_map(ud,"broad","Final broad-class UMAP",file.path(fig,"final_broad_UMAP"));if(has_subtype)plot_map(ud,"subtype","Final high-confidence subtype UMAP",file.path(fig,"final_subtype_UMAP"))
has_spatial<-FALSE
if(!is.null(a$coordinates)){co<-read_any(a$coordinates);co[[cc]]<-as.character(co[[cc]]);co<-co[match(cells,get(cc))];xx<-intersect(c("sdimx","x","spatial_x"),names(co))[1];yy<-intersect(c("sdimy","y","spatial_y"),names(co))[1];sd<-data.table(cell_id=cells,x=co[[xx]],y=co[[yy]]);has_spatial<-TRUE}else if(inherits(obj,"Seurat")&&all(c("x","y")%in%colnames(obj[[]]))){md<-obj[[]];sd<-data.table(cell_id=cells,x=as.numeric(md[cells,"x"]),y=as.numeric(md[cells,"y"]));has_spatial<-TRUE}
rows<-list();z<-1L
if(has_spatial){sd<-cbind(sd,meta[,.(broad=get(a$`broad-col`),subtype=get(a$`subtype-col`))]);plot_map(sd,"broad","Final broad-class spatial",file.path(fig,"final_broad_spatial"),TRUE);if(has_subtype)plot_map(sd,"subtype","Final high-confidence subtype spatial",file.path(fig,"final_subtype_spatial"),TRUE)
# Broad nodes are global.  Subtype nodes are broad→subtype paths rather than
# global subtype names: the same review label (for example "Unresolved") may
# legitimately occur under more than one parent, and combining those cells
# would make the expandable hierarchy and its counts misleading.
for(g in sort(unique(na.omit(as.character(sd$broad))))){if(!nzchar(g))next;d<-copy(sd);d[,selected:=as.character(broad)==g];p<-ggplot(d,aes(x,y))+scattermore::geom_scattermore(data=d[selected==FALSE],colour="#E2E2E2",pointsize=.4,pixels=c(1600,1600))+scattermore::geom_scattermore(data=d[selected==TRUE],colour="#D62728",pointsize=.85,pixels=c(1600,1600))+scale_y_reverse()+coord_equal()+theme_void()+labs(title=paste0(g," (n=",sum(d$selected),")"));stem<-file.path(node_dir,paste0("broad__",safe(g)));save_both(p,stem);rows[[z]]<-data.table(level="broad",parent_label="",label=g,n_observations=sum(d$selected),png=paste0(stem,".png"),pdf=paste0(stem,".pdf"));z<-z+1L}
pairs<-unique(sd[!is.na(broad)&nzchar(as.character(broad))&!is.na(subtype)&nzchar(as.character(subtype)),.(broad=as.character(broad),subtype=as.character(subtype))]);setorder(pairs,broad,subtype)
for(i in seq_len(nrow(pairs))){parent<-pairs$broad[i];g<-pairs$subtype[i];d<-copy(sd);d[,selected:=as.character(broad)==parent&as.character(subtype)==g];title<-paste0(parent," → ",g," (n=",sum(d$selected),")");p<-ggplot(d,aes(x,y))+scattermore::geom_scattermore(data=d[selected==FALSE],colour="#E2E2E2",pointsize=.4,pixels=c(1600,1600))+scattermore::geom_scattermore(data=d[selected==TRUE],colour="#D62728",pointsize=.85,pixels=c(1600,1600))+scale_y_reverse()+coord_equal()+theme_void()+labs(title=title);stem<-file.path(node_dir,paste0("subtype__",safe(parent),"__",safe(g)));save_both(p,stem);rows[[z]]<-data.table(level="subtype",parent_label=parent,label=g,n_observations=sum(d$selected),png=paste0(stem,".png"),pdf=paste0(stem,".pdf"));z<-z+1L}}
if(length(rows))fwrite(rbindlist(rows),file.path(a$out,"tables","spatial_node_asset_index.tsv"),sep="\t")
