#!/usr/bin/env Rscript

suppressPackageStartupMessages({library(Seurat);library(SeuratObject);library(data.table);library(ggplot2);library(scattermore);library(patchwork)})
parse_args<-function(x){o<-list();i<-1L;while(i<=length(x)){k<-sub("^--","",x[i]);if(i==length(x)||startsWith(x[i+1],"--")){o[[k]]<-TRUE;i<-i+1L}else{o[[k]]<-x[i+1];i<-i+2L}};o};a<-parse_args(commandArgs(trailingOnly=TRUE))
need<-c("rds","metadata","out","cell-id-col","broad-col","subtype-col");m<-need[!need%in%names(a)];if(length(m))stop("Missing: ",paste(m,collapse=", "))
dir.create(a$out,recursive=TRUE,showWarnings=FALSE);node_dir<-file.path(a$out,"spatial_nodes");dir.create(node_dir,showWarnings=FALSE);fig<-file.path(a$out,"figures");dir.create(fig,showWarnings=FALSE);dir.create(file.path(a$out,"tables"),showWarnings=FALSE)
read_any<-function(p)if(grepl("\\.gz$",p))fread(cmd=paste("gzip -dc",shQuote(p)))else fread(p)
save_both<-function(p,stem,w=9,h=7){ggsave(paste0(stem,".png"),p,width=w,height=h,dpi=400,bg="white",limitsize=FALSE);ggsave(paste0(stem,".pdf"),p,width=w,height=h,device=cairo_pdf,bg="white",limitsize=FALSE)}
safe<-function(x)substr(gsub("_+","_",gsub("[^A-Za-z0-9_.-]+","_",x)),1,150)
obj<-readRDS(a$rds);meta<-read_any(a$metadata);cc<-a$`cell-id-col`;meta[[cc]]<-as.character(meta[[cc]]);stopifnot(uniqueN(meta[[cc]])==nrow(meta));cells<-intersect(colnames(obj),meta[[cc]]);if(!length(cells))stop("No matching IDs");meta<-meta[match(cells,get(cc))]
plot_map<-function(d,group,title,stem,spatial=FALSE){d[,label:=as.character(get(group))];d<-d[!is.na(label)&nzchar(label)];lev<-sort(unique(d$label));pal<-setNames(hcl.colors(length(lev),"Dark 3"),lev);p<-ggplot(d,aes(x,y,colour=label))+scattermore::geom_scattermore(pointsize=ifelse(spatial,.82,.75),pixels=c(2200,2200))+scale_colour_manual(values=pal)+theme_classic(base_size=8)+labs(title=title,colour=NULL);if(spatial)p<-p+scale_y_reverse()+coord_equal()+theme_void()+labs(title=title);save_both(p,stem)}
has_state_col<-!is.null(a$`state-col`);if(has_state_col&&!a$`state-col`%in%names(meta))stop("state-col absent from metadata")
has_subtype<-any(!is.na(meta[[a$`subtype-col`]])&nzchar(as.character(meta[[a$`subtype-col`]])));has_state<-has_state_col&&any(!is.na(meta[[a$`state-col`]])&nzchar(as.character(meta[[a$`state-col`]])))
if(is.null(a$`skip-umap`)){if(!is.null(a$umap)){um<-read_any(a$umap);um[[cc]]<-as.character(um[[cc]]);um<-um[match(cells,get(cc))];ux<-intersect(c("UMAP_1","umap_1","UMAP1"),names(um))[1];uy<-intersect(c("UMAP_2","umap_2","UMAP2"),names(um))[1];ud<-data.table(cell_id=cells,x=um[[ux]],y=um[[uy]])}else if(inherits(obj,"Seurat")){red<-ifelse(is.null(a$reduction),"umap",a$reduction);em<-Embeddings(obj,red)[cells,1:2,drop=FALSE];ud<-data.table(cell_id=cells,x=em[,1],y=em[,2])}else if(inherits(obj,"SingleCellExperiment")){if(!requireNamespace("SingleCellExperiment",quietly=TRUE))stop("SingleCellExperiment package required");red<-ifelse(is.null(a$reduction),"UMAP",a$reduction);em<-SingleCellExperiment::reducedDim(obj,red)[cells,1:2,drop=FALSE];ud<-data.table(cell_id=cells,x=em[,1],y=em[,2])}else stop("Supply --umap for this object class");ud<-cbind(ud,meta[,.(broad=get(a$`broad-col`),subtype=get(a$`subtype-col`),state=if(has_state_col)get(a$`state-col`) else "")]);plot_map(ud,"broad","Final broad-class UMAP",file.path(fig,"final_broad_UMAP"));if(has_subtype)plot_map(ud,"subtype","Final high-confidence subtype UMAP",file.path(fig,"final_subtype_UMAP"));if(has_state)plot_map(ud,"state","Final supported state UMAP",file.path(fig,"final_state_UMAP"))}
has_spatial<-FALSE
if(!is.null(a$coordinates)){co<-read_any(a$coordinates);co[[cc]]<-as.character(co[[cc]]);co<-co[match(cells,get(cc))];xx<-intersect(c("sdimx","x","spatial_x"),names(co))[1];yy<-intersect(c("sdimy","y","spatial_y"),names(co))[1];if(is.na(xx)||is.na(yy))stop("coordinates lack x/y columns");sd<-data.table(cell_id=cells,x=co[[xx]],y=co[[yy]]);has_spatial<-TRUE}else if(inherits(obj,"Seurat")&&all(c("x","y")%in%colnames(obj[[]]))){md<-obj[[]];sd<-data.table(cell_id=cells,x=as.numeric(md[cells,"x"]),y=as.numeric(md[cells,"y"]));has_spatial<-TRUE}
rows<-list();z<-1L
if(has_spatial){sd<-cbind(sd,meta[,.(broad=get(a$`broad-col`),subtype=get(a$`subtype-col`),state=if(has_state_col)get(a$`state-col`) else "")]);plot_map(sd,"broad","Final broad-class spatial",file.path(fig,"final_broad_spatial"),TRUE);if(has_subtype)plot_map(sd,"subtype","Final high-confidence subtype spatial",file.path(fig,"final_subtype_spatial"),TRUE);if(has_state)plot_map(sd,"state","Final supported state spatial",file.path(fig,"final_state_spatial"),TRUE)
highlight<-function(d,selected,title,stem,level,parent,label){p<-ggplot(d,aes(x,y))+scattermore::geom_scattermore(data=d[!selected],colour="#C9C9C9",pointsize=.55,pixels=c(1600,1600))+scattermore::geom_scattermore(data=d[selected],colour="#C00020",pointsize=.9,pixels=c(1600,1600))+scale_y_reverse()+coord_equal()+theme_void()+labs(title=title);save_both(p,stem);rows[[z]]<<-data.table(level=level,parent_label=parent,label=label,n_observations=sum(selected),png=paste0(stem,".png"),pdf=paste0(stem,".pdf"));z<<-z+1L}
for(g in sort(unique(na.omit(as.character(sd$broad))))){if(nzchar(g)){sel<-as.character(sd$broad)==g;highlight(sd,sel,paste0(g," (n=",sum(sel),")"),file.path(node_dir,paste0("broad__",safe(g))),"broad","",g)}}
pairs<-unique(sd[!is.na(broad)&nzchar(as.character(broad))&!is.na(subtype)&nzchar(as.character(subtype)),.(broad=as.character(broad),subtype=as.character(subtype))]);setorder(pairs,broad,subtype);for(i in seq_len(nrow(pairs))){parent<-pairs$broad[i];g<-pairs$subtype[i];sel<-as.character(sd$broad)==parent&as.character(sd$subtype)==g;highlight(sd,sel,paste0(parent," → ",g," (n=",sum(sel),")"),file.path(node_dir,paste0("subtype__",safe(parent),"__",safe(g))),"subtype",parent,g)}
if(has_state){for(g in sort(unique(na.omit(as.character(sd$state))))){if(nzchar(g)){sel<-as.character(sd$state)==g;highlight(sd,sel,paste0(g," state (n=",sum(sel),")"),file.path(node_dir,paste0("state__",safe(g))),"state","",g)}}}}
if(length(rows))fwrite(rbindlist(rows),file.path(a$out,"tables","spatial_node_asset_index.tsv"),sep="\t")
