#!/usr/bin/env Rscript

suppressPackageStartupMessages({library(Seurat);library(SeuratObject);library(Matrix);library(data.table)})
parse_args<-function(x){o<-list();i<-1L;while(i<=length(x)){k<-sub("^--","",x[i]);if(i==length(x)||startsWith(x[i+1],"--")){o[[k]]<-TRUE;i<-i+1L}else{o[[k]]<-x[i+1];i<-i+2L}};o};a<-parse_args(commandArgs(trailingOnly=TRUE));need<-c("rds","metadata","out","cell-id-col","broad-col","subtype-col");m<-need[!need%in%names(a)];if(length(m))stop("Missing: ",paste(m,collapse=", "))
dir.create(file.path(a$out,"tables"),recursive=TRUE,showWarnings=FALSE);dir.create(file.path(a$out,"provenance"),recursive=TRUE,showWarnings=FALSE);read_any<-function(p)if(grepl("\\.gz$",p))fread(cmd=paste("gzip -dc",shQuote(p)))else fread(p);obj<-readRDS(a$rds);meta<-read_any(a$metadata);cc<-a$`cell-id-col`;meta[[cc]]<-as.character(meta[[cc]]);cells<-intersect(colnames(obj),meta[[cc]]);meta<-meta[match(cells,get(cc))];seed<-as.integer(ifelse(is.null(a$seed),20260713,a$seed));max_cells<-as.integer(ifelse(is.null(a$`max-cells-per-ident`),3000,a$`max-cells-per-ident`));set.seed(seed)
prefix<-ifelse(is.null(a$prefix),"",paste0(a$prefix,"_"));analysis_view<-ifelse(is.null(a$`analysis-view`),ifelse(nzchar(prefix),sub("_$","",prefix),"provided_labels"),a$`analysis-view`);evidence_cohort<-ifelse(is.null(a$`evidence-cohort`),"provided_metadata",a$`evidence-cohort`)
if(!is.null(a$`include-col`)){allowed<-strsplit(a$`include-values`,",",fixed=TRUE)[[1]];meta<-meta[tolower(as.character(get(a$`include-col`)))%in%tolower(allowed)];cells<-meta[[cc]]}
write_level<-function(level,col){labels<-as.character(meta[[col]]);valid<-!is.na(labels)&nzchar(labels);labs<-sort(unique(labels[valid]));if(length(labs)<2)stop(level," has fewer than two labels")
if(inherits(obj,"Seurat")){q<-subset(obj,cells=cells[valid]);assay<-ifelse(is.null(a$assay),DefaultAssay(q),a$assay);DefaultAssay(q)<-assay;Idents(q)<-factor(labels[valid],levels=labs);deg<-as.data.table(FindAllMarkers(q,assay=assay,slot=ifelse(is.null(a$layer),"data",a$layer),only.pos=TRUE,test.use="wilcox",min.pct=.05,logfc.threshold=.1,return.thresh=1,max.cells.per.ident=max_cells,random.seed=seed,densify=FALSE,verbose=TRUE));setnames(deg,"cluster","label")
}else if(inherits(obj,"SingleCellExperiment")||inherits(obj,"SummarizedExperiment")){if(!requireNamespace("SummarizedExperiment",quietly=TRUE))stop("SummarizedExperiment required");available<-SummarizedExperiment::assayNames(obj);data_name<-if(!is.null(a$`data-assay`))a$`data-assay` else if("normcounts"%in%available)"normcounts" else if("logcounts"%in%available)"logcounts" else stop("Specify --data-assay");count_name<-if(!is.null(a$`count-assay`))a$`count-assay` else "counts";nor<-SummarizedExperiment::assay(obj,data_name)[,cells[valid],drop=FALSE];cts<-SummarizedExperiment::assay(obj,count_name)[,cells[valid],drop=FALSE];grp<-factor(labels[valid],levels=labs);G<-sparse.model.matrix(~0+grp);colnames(G)<-labs;n<-colSums(G);sn<-as.matrix(nor%*%G);det<-as.matrix((cts>0)%*%G);avg<-sweep(sn,2,n,"/");pct<-100*sweep(det,2,n,"/");tot<-Matrix::rowSums(nor);deg<-rbindlist(lapply(seq_along(labs),function(j){rest<-(tot-sn[,j])/(sum(valid)-n[j]);data.table(gene=rownames(obj),label=labs[j],avg_expression=avg[,j],pct_expressed_absolute=pct[,j],avg_expression_rest=rest,avg_log2FC=log2((avg[,j]+1e-4)/(rest+1e-4)),n_observations=n[j])}));setorder(deg,label,-avg_log2FC)
}else stop("Unsupported object class")
deg[,`:=`(analysis_view=analysis_view,evidence_cohort=evidence_cohort)];fwrite(deg,file.path(a$out,"tables",paste0(prefix,level,"_DEG_one_vs_rest_all.tsv")),sep="\t");lfc<-intersect(c("avg_log2FC","avg_logFC"),names(deg))[1];if("p_val_adj"%in%names(deg))top<-deg[p_val_adj<.05&get(lfc)>0][order(label,p_val_adj,-get(lfc)),head(.SD,100),by=label]else top<-deg[order(label,-get(lfc)),head(.SD,100),by=label];fwrite(top,file.path(a$out,"tables",paste0(prefix,level,"_DEG_top100.tsv")),sep="\t")}
write_level("broad",a$`broad-col`);write_level("subtype",a$`subtype-col`);writeLines(capture.output(sessionInfo()),file.path(a$out,"provenance","DEG_sessionInfo.txt"))
