#!/usr/bin/env Rscript

suppressPackageStartupMessages({library(Matrix);library(data.table);library(spacexr);library(jsonlite)})
parse_args<-function(x){o<-list();i<-1L;while(i<=length(x)){k<-sub("^--","",x[i]);if(i==length(x)||startsWith(x[i+1],"--")){o[[k]]<-TRUE;i<-i+1L}else{o[[k]]<-x[i+1];i<-i+2L}};o};a<-parse_args(commandArgs(trailingOnly=TRUE));need<-c("query-rds","query-membership","coordinates","reference-rds","reference-metadata","out","cell-id-col","reference-cell-id-col","reference-label-col","umi-min","counts-min");miss<-need[!need%in%names(a)];if(length(miss))stop("Missing: ",paste(miss,collapse=", "))
dir.create(a$out,recursive=TRUE,showWarnings=FALSE);read_any<-function(p)if(grepl("\\.gz$",p))fread(cmd=paste("gzip -dc",shQuote(p)))else fread(p)
extract_counts<-function(obj,assay_name=NULL,count_name="counts"){
 if(inherits(obj,"Seurat")){if(!requireNamespace("SeuratObject",quietly=TRUE))stop("SeuratObject required");an<-if(is.null(assay_name))SeuratObject::DefaultAssay(obj)else assay_name;tryCatch(SeuratObject::LayerData(obj[[an]],layer=count_name),error=function(e)SeuratObject::GetAssayData(obj[[an]],slot=count_name))}
 else if(inherits(obj,"SummarizedExperiment")){SummarizedExperiment::assay(obj,count_name)}else stop("Unsupported object")}
qobj<-readRDS(a$`query-rds`);robj<-readRDS(a$`reference-rds`);cc<-a$`cell-id-col`;rc<-a$`reference-cell-id-col`;mem<-read_any(a$`query-membership`);co<-read_any(a$coordinates);rm<-read_any(a$`reference-metadata`);mem[[cc]]<-as.character(mem[[cc]]);co[[cc]]<-as.character(co[[cc]]);rm[[rc]]<-as.character(rm[[rc]])
if(uniqueN(mem[[cc]])!=nrow(mem))stop("duplicate query membership");qids<-intersect(colnames(qobj),mem[[cc]]);if(length(qids)!=nrow(mem))stop("query membership mismatch");co<-co[match(qids,get(cc))];if(anyNA(co[[cc]]))stop("coordinate mismatch");xcol<-if(!is.null(a$`x-col`))a$`x-col` else intersect(c("sdimx","x","spatial_x"),names(co))[1];ycol<-if(!is.null(a$`y-col`))a$`y-col` else intersect(c("sdimy","y","spatial_y"),names(co))[1]
qcts<-extract_counts(qobj,a$`query-assay`,ifelse(is.null(a$`query-count-assay`),"counts",a$`query-count-assay`))[,qids,drop=FALSE];rids<-intersect(colnames(robj),rm[[rc]]);rm<-rm[match(rids,get(rc))];rcts<-extract_counts(robj,a$`reference-assay`,ifelse(is.null(a$`reference-count-assay`),"counts",a$`reference-count-assay`))[,rids,drop=FALSE];genes<-intersect(rownames(qcts),rownames(rcts));if(length(genes)<200)stop("fewer than 200 shared genes");qcts<-qcts[genes,,drop=FALSE];rcts<-rcts[genes,,drop=FALSE]
coords<-data.frame(x=as.numeric(co[[xcol]]),y=as.numeric(co[[ycol]]),row.names=qids);ctype<-factor(rm[[a$`reference-label-col`]]);names(ctype)<-rids;sp<-SpatialRNA(coords,qcts,nUMI=Matrix::colSums(qcts),require_int=TRUE);ref<-Reference(rcts,ctype,nUMI=Matrix::colSums(rcts),require_int=TRUE,min_UMI=as.integer(ifelse(is.null(a$`reference-min-umi`),1,a$`reference-min-umi`)))
cores<-as.integer(ifelse(is.null(a$cores),4,a$cores));umi_sigma<-as.integer(ifelse(is.null(a$`umi-min-sigma`),a$`umi-min`,a$`umi-min-sigma`));test_mode<-!is.null(a$`test-mode`)&&tolower(as.character(a$`test-mode`))%in%c("true","1","yes");rctd<-create.RCTD(sp,ref,max_cores=cores,test_mode=test_mode,UMI_min=as.integer(a$`umi-min`),UMI_min_sigma=umi_sigma,counts_MIN=as.integer(a$`counts-min`),keep_reference=TRUE);rctd<-run.RCTD(rctd,doublet_mode=ifelse(is.null(a$`doublet-mode`),"doublet",a$`doublet-mode`));saveRDS(rctd,file.path(a$out,"rctd_review_object.rds"),compress=FALSE)
res<-tryCatch(as.data.table(rctd@results$results_df,keep.rownames="cell_id"),error=function(e)data.table());weights<-tryCatch(as.data.table(as.matrix(rctd@results$weights),keep.rownames="cell_id"),error=function(e)data.table());fwrite(res,file.path(a$out,"rctd_results.tsv"),sep="\t");fwrite(weights,file.path(a$out,"rctd_weights.tsv"),sep="\t");write_json(list(status="EVIDENCE_ONLY",n_query=ncol(qcts),n_reference=ncol(rcts),shared_genes=length(genes),umi_min=as.integer(a$`umi-min`),umi_min_sigma=umi_sigma,counts_min=as.integer(a$`counts-min`),doublet_mode=ifelse(is.null(a$`doublet-mode`),"doublet",a$`doublet-mode`),warning="Calibrate on held-out/downsampled anchors; RCTD output cannot directly write labels."),file.path(a$out,"rctd_manifest.json"),pretty=TRUE,auto_unbox=TRUE);writeLines(capture.output(sessionInfo()),file.path(a$out,"sessionInfo.txt"))
