#!/usr/bin/env Rscript

suppressPackageStartupMessages({library(SingleCellExperiment);library(SummarizedExperiment);library(Matrix);library(data.table);library(ggplot2);library(scattermore);library(patchwork)})
parse_args<-function(x){o<-list();i<-1L;while(i<=length(x)){k<-sub("^--","",x[i]);if(i==length(x)||startsWith(x[i+1],"--")){o[[k]]<-TRUE;i<-i+1L}else{o[[k]]<-x[i+1];i<-i+2L}};o};a<-parse_args(commandArgs(trailingOnly=TRUE))
need<-c("rds","clusters","out","cell-id-col","cluster-col");m<-need[!need%in%names(a)];if(length(m))stop("Missing: ",paste(m,collapse=", "))
dir.create(file.path(a$out,"tables"),recursive=TRUE,showWarnings=FALSE);dir.create(file.path(a$out,"figures"),recursive=TRUE,showWarnings=FALSE)
read_any<-function(p)if(grepl("\\.gz$",p))fread(cmd=paste("gzip -dc",shQuote(p)))else fread(p);save_both<-function(p,stem,w,h){ggsave(paste0(stem,".png"),p,width=w,height=h,dpi=360,bg="white",limitsize=FALSE);ggsave(paste0(stem,".pdf"),p,width=w,height=h,device=cairo_pdf,bg="white",limitsize=FALSE)}
sce<-readRDS(a$rds);stopifnot(inherits(sce,"SingleCellExperiment"));available<-assayNames(sce);count_name<-ifelse(is.null(a$`count-assay`),"counts",a$`count-assay`);data_name<-if(!is.null(a$`data-assay`))a$`data-assay` else if("normcounts"%in%available)"normcounts" else if("logcounts"%in%available)"logcounts" else stop("Specify --data-assay")
stopifnot(count_name%in%available,data_name%in%available);cl<-read_any(a$clusters);cc<-a$`cell-id-col`;cl[[cc]]<-as.character(cl[[cc]]);stopifnot(uniqueN(cl[[cc]])==nrow(cl));ids<-as.character(colnames(sce));if(!setequal(ids,cl[[cc]]))stop("SCE and clustering IDs differ");cl<-cl[match(ids,get(cc))];grp<-factor(as.character(cl[[a$`cluster-col`]]),levels=sort(unique(as.character(cl[[a$`cluster-col`]]))));lev<-levels(grp)
G<-sparse.model.matrix(~0+grp);colnames(G)<-lev;cts<-assay(sce,count_name);nor<-assay(sce,data_name);n<-as.numeric(table(grp));names(n)<-lev;sum_nor<-as.matrix(nor%*%G);det<-as.matrix((cts>0)%*%G);avg<-sweep(sum_nor,2,n,"/");pct<-100*sweep(det,2,n,"/");tot<-Matrix::rowSums(nor);ntot<-ncol(sce)
rows<-lapply(seq_along(lev),function(j){rest<-(tot-sum_nor[,j])/(ntot-n[j]);lfc<-log2((avg[,j]+1e-4)/(rest+1e-4));data.table(gene=rownames(sce),cluster=lev[j],avg_expression=avg[,j],pct_expressed_absolute=pct[,j],avg_expression_rest=rest,avg_log2FC=lfc,specificity_score=lfc*sqrt(pmax(pct[,j],0)/100),n_observations=n[j])});deg<-rbindlist(rows);setorder(deg,cluster,-specificity_score);fwrite(deg,file.path(a$out,"tables","cluster_DEG_one_vs_rest_all.tsv"),sep="\t");fwrite(deg[,head(.SD,100),by=cluster],file.path(a$out,"tables","cluster_DEG_top100_positive.tsv"),sep="\t");fwrite(data.table(cluster=lev,n_observations=n),file.path(a$out,"tables","cluster_counts.tsv"),sep="\t")
xx<-intersect(c("sdimx","x","spatial_x"),names(cl))[1];yy<-intersect(c("sdimy","y","spatial_y"),names(cl))[1];if(is.na(xx)||is.na(yy))stop("Cluster table lacks spatial coordinates");sp<-data.table(x=as.numeric(cl[[xx]]),y=as.numeric(cl[[yy]]),cluster=grp);pal<-setNames(hcl.colors(length(lev),"Dynamic"),lev);title<-ifelse(is.null(a$title),"Selected clustering",a$title);p1<-ggplot(sp,aes(x,y,colour=cluster))+geom_scattermore(pointsize=.45,pixels=c(2200,2200))+scale_colour_manual(values=pal)+scale_y_reverse()+coord_equal()+theme_void()+labs(title=paste(title,"spatial"),colour="cluster");save_both(p1,file.path(a$out,"figures","selected_clustering_spatial"),10,8)
if(!is.null(a$umap)){um<-read_any(a$umap);um[[cc]]<-as.character(um[[cc]]);um<-um[match(ids,get(cc))];ux<-intersect(c("UMAP_1","umap_1","UMAP1"),names(um))[1];uy<-intersect(c("UMAP_2","umap_2","UMAP2"),names(um))[1];ud<-data.table(x=as.numeric(um[[ux]]),y=as.numeric(um[[uy]]),cluster=grp);p2<-ggplot(ud,aes(x,y,colour=cluster))+geom_scattermore(pointsize=.5,pixels=c(2200,2200))+scale_colour_manual(values=pal)+theme_classic(base_size=8)+labs(title=paste(title,"UMAP"),colour="cluster");save_both(p2,file.path(a$out,"figures","selected_clustering_UMAP"),10,8)}
plots<-lapply(lev,function(k){d<-copy(sp);d[,selected:=cluster==k];ggplot(d,aes(x,y))+geom_scattermore(data=d[selected==FALSE],colour="#E3E3E3",pointsize=.3,pixels=c(900,900))+geom_scattermore(data=d[selected==TRUE],colour="#D62728",pointsize=.8,pixels=c(900,900))+scale_y_reverse()+coord_equal()+theme_void()+labs(title=paste0("c",k," (n=",sum(d$selected),")"))+theme(plot.title=element_text(size=7,hjust=.5))});pg<-wrap_plots(plots,ncol=4)+plot_annotation(title="Per-cluster spatial highlights");save_both(pg,file.path(a$out,"figures","selected_clustering_highlight_grid"),13,ceiling(length(lev)/4)*3)
fwrite(data.table(parameter=c("object_class","n_features","n_observations","count_assay","data_assay","deg_method"),value=c(class(sce)[1],nrow(sce),ncol(sce),count_name,data_name,"aggregate normalized mean/detection one-vs-rest log2FC")),file.path(a$out,"evidence_run_manifest.tsv"),sep="\t");writeLines(capture.output(sessionInfo()),file.path(a$out,"sessionInfo.txt"))

