#!/usr/bin/env Rscript

suppressPackageStartupMessages({library(Seurat);library(SeuratObject);library(Matrix);library(data.table);library(jsonlite)})
parse_args<-function(x){o<-list();i<-1L;while(i<=length(x)){k<-sub("^--","",x[i]);if(i==length(x)||startsWith(x[i+1],"--")){o[[k]]<-TRUE;i<-i+1L}else{o[[k]]<-x[i+1];i<-i+2L}};o};a<-parse_args(commandArgs(trailingOnly=TRUE));need<-c("rds","membership","profile","rule","out","cell-id-col");m<-need[!need%in%names(a)];if(length(m))stop("Missing: ",paste(m,collapse=", "))
dir.create(a$out,recursive=TRUE,showWarnings=FALSE);read_any<-function(p)if(grepl("\\.gz$",p))fread(cmd=paste("gzip -dc",shQuote(p)))else fread(p);obj<-readRDS(a$rds);mem<-read_any(a$membership);cc<-a$`cell-id-col`;mem[[cc]]<-as.character(mem[[cc]]);cells<-intersect(colnames(obj),mem[[cc]]);if(length(cells)!=nrow(mem))stop("Membership IDs do not exactly match object");profile<-fromJSON(a$profile,simplifyVector=FALSE);rule<-profile$rare_cell_rules[[a$rule]];if(is.null(rule))stop("Rule not found: ",a$rule)
zona<-unlist(rule$zona_markers);identity_markers<-unlist(rule$identity_markers);maternal<-unlist(rule$maternal_ooplasm);identity<-unlist(rule$identity_core);contra<-unlist(rule$contradictory_somatic);genes<-unique(c(zona,identity_markers,maternal,identity,contra))
if(inherits(obj,"Seurat")){assay<-ifelse(is.null(a$assay),DefaultAssay(obj),a$assay);count_layer<-ifelse(is.null(a$`count-layer`),"counts",a$`count-layer`);data_layer<-ifelse(is.null(a$`data-layer`),"data",a$`data-layer`);cts<-tryCatch(LayerData(obj[[assay]],layer=count_layer),error=function(e)GetAssayData(obj[[assay]],slot=count_layer));nor<-tryCatch(LayerData(obj[[assay]],layer=data_layer),error=function(e)GetAssayData(obj[[assay]],slot=data_layer))
}else if(inherits(obj,"SingleCellExperiment")||inherits(obj,"SummarizedExperiment")){if(!requireNamespace("SummarizedExperiment",quietly=TRUE))stop("SummarizedExperiment required");av<-SummarizedExperiment::assayNames(obj);cn<-ifelse(is.null(a$`count-assay`),"counts",a$`count-assay`);dn<-if(!is.null(a$`data-assay`))a$`data-assay` else if("normcounts"%in%av)"normcounts" else if("logcounts"%in%av)"logcounts" else stop("Specify --data-assay");cts<-SummarizedExperiment::assay(obj,cn);nor<-SummarizedExperiment::assay(obj,dn)
}else stop("Unsupported object class");present<-intersect(genes,rownames(cts));missing<-setdiff(genes,present);cts<-cts[present,cells,drop=FALSE];nor<-nor[present,cells,drop=FALSE]
hits<-function(g){g<-intersect(g,present);if(!length(g))return(rep(0,length(cells)));Matrix::colSums(cts[g,,drop=FALSE]>0)};score<-function(g){g<-intersect(g,present);if(!length(g))return(rep(0,length(cells)));Matrix::colMeans(nor[g,,drop=FALSE])}
out<-data.table(cell_id=cells,zona_hits=hits(zona),identity_marker_hits=hits(identity_markers),maternal_ooplasm_hits=hits(maternal),identity_core_hits=hits(identity),total_oocyte_program_hits=hits(c(zona,identity)),contradictory_somatic_hits=hits(contra),zona_score=score(zona),identity_core_score=score(identity),contradictory_somatic_score=score(contra));min_total<-as.integer(rule$starting_min_total_markers);min_identity<-as.integer(rule$starting_min_identity_core);min_modules<-as.integer(ifelse(is.null(rule$starting_required_modules),2,rule$starting_required_modules));out[,modules_detected:=(zona_hits>0L)+(identity_marker_hits>0L)+(maternal_ooplasm_hits>0L)];out[,starting_marker_gate:=total_oocyte_program_hits>=min_total & identity_core_hits>=min_identity & modules_detected>=min_modules];out<-merge(out,mem,by.x="cell_id",by.y=cc,all.x=TRUE,sort=FALSE);fwrite(out,file.path(a$out,paste0(a$rule,"_cell_program_screen.tsv.gz")),sep="\t")
summary<-list(rule=a$rule,n_membership=nrow(out),genes_present=present,genes_missing=missing,starting_min_total=min_total,starting_min_identity=min_identity,starting_min_modules=min_modules,starting_gate_n=sum(out$starting_marker_gate),starting_gate_fraction=mean(out$starting_marker_gate),warning="Starting gate is a screening threshold, not a final biological label. Calibrate and add spatial/recluster review.");write_json(summary,file.path(a$out,paste0(a$rule,"_cell_program_screen_summary.json")),pretty=TRUE,auto_unbox=TRUE);cat(toJSON(summary,pretty=TRUE,auto_unbox=TRUE),"\n")
